MODEL:
  ROI_INPUT_SIZE: 1024
  SIFT_INPUT_SIZE: 160
  ROI_HIDDEN: 96
  SIFT_HIDDEN: 96
  IMG_HIDDEN: 128
  NUM_CLASSES: 3
  NUM_LAYERS: 2
  D_MODEL: 192
  NHEAD: 4
  DEVICE: "cuda"

DETECTRON2:
  CONFIG_PATH: "./configs/TS-RCNN-FPN.yaml"
  WEIGHT_PATH: "./model_0049999.pth"

DATA:
  TRAIN_JSON: "./data/train/sign_id_GT.json"
  TEST_JSON: "./data/test/sign_id_GT.json"
  TRAIN_IMG_ROOT: "./data/train_img"
  TEST_IMG_ROOT: "./data/test_img"

SOLVER:
  BATCH_SIZE: 8
  LR: 0.0005
  MAX_EPOCHS: 200
  CLASS_NUM: [30, 230, 30]